// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SMchHZDxNZtSNsQBTH8thz5xrzJzlJY',
    appId: '1:919540319082:web:4d6fb8fd813c5f044f1b13',
    messagingSenderId: '919540319082',
    projectId: 'gestor-tareas-1f581',
    authDomain: 'gestor-tareas-1f581.firebaseapp.com',
    storageBucket: 'gestor-tareas-1f581.firebasestorage.app',
    measurementId: 'G-2S2J46R6PL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3n3Q8Z2niPmhxFS7m8ZJPsSm5pDj8GqU',
    appId: '1:919540319082:android:ea5ae8c2114d3dce4f1b13',
    messagingSenderId: '919540319082',
    projectId: 'gestor-tareas-1f581',
    storageBucket: 'gestor-tareas-1f581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxSrkQXUjYBnuXL41Di9GKiPcY83KI-7w',
    appId: '1:919540319082:ios:5e7f2c2d9c2581034f1b13',
    messagingSenderId: '919540319082',
    projectId: 'gestor-tareas-1f581',
    storageBucket: 'gestor-tareas-1f581.firebasestorage.app',
    iosBundleId: 'com.example.gestorTareas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxSrkQXUjYBnuXL41Di9GKiPcY83KI-7w',
    appId: '1:919540319082:ios:5e7f2c2d9c2581034f1b13',
    messagingSenderId: '919540319082',
    projectId: 'gestor-tareas-1f581',
    storageBucket: 'gestor-tareas-1f581.firebasestorage.app',
    iosBundleId: 'com.example.gestorTareas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7SMchHZDxNZtSNsQBTH8thz5xrzJzlJY',
    appId: '1:919540319082:web:fffb4b511b21b3b24f1b13',
    messagingSenderId: '919540319082',
    projectId: 'gestor-tareas-1f581',
    authDomain: 'gestor-tareas-1f581.firebaseapp.com',
    storageBucket: 'gestor-tareas-1f581.firebasestorage.app',
    measurementId: 'G-LKH834ENT8',
  );
}
